#!/usr/bin/ash
# Thanks to Patryk Jaworski's and his mkinitcpio-squashfs package for the help.

mount_handler_unsqaushtmpfs () {

    local device devmnt pathtosquash

    # Device existence test
    device="${squashimgpath%%:*}"
    if [ ! -b "$device" ]; then
        _device="$device"
        device=$(blkid -lt "$device" -o device)
    fi
    if [ ! "$device" ]; then
        err  "Device not detected: "$_device"."
        echo "device= define correctly to continue."
        launch_interactive_shell
        msg  "Trying to continue..."
    fi

    # Device mount
    devmnt=/mnt/"${device##*/}"
    mkdir -p "$devmnt"
    if ! mount -o ro "$device" "$devmnt"; then
        err  "Mount error: "$device" to "$devmnt"."
        launch_interactive_shell
        msg  "Trying to continue..."
    fi

    # SquashFS image existence test
    pathtosquash="$devmnt"/"${squashimgpath##*:}"
    if [ ! -f "$pathtosquash" ]; then
        err  "SquashFS image not found: "$path"."
        echo "pathtosquash=/mnt/device/file.squashfs define correctly."
        launch_interactive_shell
        msg  "Trying to continue..."
    fi

    # squashtmpsize= existence test
    if [ ! "$squashtmpsize" ]; then
        err  "squashtmpsize= not specified."
        echo "Specify squashtmpsize= in # (bytes), or #M, or #G."
        launch_interactive_shell
        msg  "Trying to continue..."
    fi

    # Tmpfs create
    if ! mount -t tmpfs tmpfs -o rw,size="$squashtmpsize",relatime "$1"; then
        err  "Tmpfs creation failed."
        echo "It may be possible the system does not have enough memory."
        launch_interactive_shell
        msg  "Trying to continue..."
    fi

    # SquashFS image decompress
    if ! unsquashfs -dest "$1" -force "$pathtosquash"; then
        err  "SquashFS decompression failed."
        echo "Does squashtmpsize= specify enough memory?"
        launch_interactive_shell
        msg  "Trying to continue..."
    fi

}

run_hook() {

    mount_handler=mount_handler_unsqaushtmpfs

}

# vim: ai ts=4 sw=4 ft=sh:
