#!/usr/bin/ash

build() {
    add_binary /usr/bin/eject
    add_binary /usr/bin/unsquashfs
    add_runscript
}

help() {
	cat <<EOF
==> Help for hook unsquashtmpfs
This hook decompresses a root directory, gzipped, squashfs image and mounts it to a tmpfs filesystem (i.e. memory).  This is really only useful for an install disk.  It adds and requires these kernel parameters (for device: kernel device name, LABEL, or UUID can be used):

 root=/new_root
 squashimgpath=[/device/...]:[/path/to/file.squashfs]
 squashtmpsize=[number of bytes]

 HOOKS="... block unsquashtmpfs filesystems ..."
EOF
}

# vim: ai ts=4 sw=4 ft=sh:
